# Default values for settings.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: registry.gitlab.com/lyra-egnify/hydra-graphql-api-gateway/spark/development
  tag: latest
  pullPolicy: Always
  pullSecrets: gitlab-registry-pull-secret

#project env
projectEnv:
  nodeEnv: "production"
  mongodbUri: "mongodb://hydra:AkdjsAIYHjk87y23l1m2klRrtyhjnmrti92w33@35.200.218.1:27017/tenantregistry"
  jwtSecret: "KAJDK656kllksklfmFGDFGS765ujh765T6GHAJDSjjjkjiursrda"
  mailjetApiKey: "a1fb4988b5a359099061d2cb8aebc80d"
  apolloEngineKey: "service:hydra-jeet-dev:b9DCNb7tCkPO6TO5xHIdmw"
  svcSettings: "http://settings-dev-spark.dev.svc.cluster.local"
  svcTest: "http://test-management-dev-spark.dev.svc.cluster.local"

service:
  name: spark-gateway
  tier: backend
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - api.dev.spark.egnify.io
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "40M"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: spark-graphql-gateway-tls-dev
      hosts:
        - api.dev.spark.egnify.io
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
